### ISSUE TITLE
/handsontable/handsontable-skeleton/blob/master/plugins/internal

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable-skeleton#1]
In page 
https://github.com/handsontable/handsontable-skeleton 
both Internal plugins and External plugins move to the same page - https://github.com/handsontable/handsontable-skeleton/tree/master/plugins/internal

**Comment by jansiegel** [comment]
@pnowak, you're right - it should be fine now. 
Thanks for noticing!
