### ISSUE TITLE
registerPlugin is not function

### ISSUE THREAD

**Issue by jinan5694** [handsontable/handsontable-skeleton#2]
i want write a external plugin and i catch a error.
Handontable.plugins.registerPlugin is not a function

i see the object from console,there is not found this function too.
is there any problem about it?

**Comment by tmesquita** [comment]
I'm guessing you are probably using a version between 0.20.1 and 0.22.0. If you look at their release logs it looks like it went missing in 0.20.1 and was re-added in 0.22.0.  

https://github.com/handsontable/handsontable/releases/tag/0.22.0
