### ISSUE TITLE
How can I develop a plugin of Handontable?

### ISSUE THREAD

**Issue by rollinstar** [handsontable/handsontable-skeleton#3]
Hi
Thank you for providing this project.
I am trying to develop a plugin of Handontable using this project.
So, I downloaded this project from Git, and then build a sources.
But it couldn't be conducted.
Is there anyone who developed plugin of Handontable using this project?
Or is this project terminated?

Actually, my English skill is not good so some sentences may be grammatically wrong. If you cannot understand my question, leave a comment please.

**Comment by AMBudnik** [comment]
`Continued at email support channel`

**Comment by rollinstar** [comment]
Thank you!
I read your email. I will reply to you and close this issue.
